urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

from settings import UNALOG_ROOT

admin.autodiscover()


urlpatterns = patterns('',
    # NOTE: don't enable this for real.
    (r'^s/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': "%s/base/media" % UNALOG_ROOT}),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^login/$', 'django.contrib.auth.views.login', 
        {'template_name': 'login.html'}, name='login'),

    )

urlpatterns += patterns('base.views',
    # Site-wide
    url(r'^$', 'index', name='index'),
    url(r'^feed/$', 'feed', name='feed'),
    url(r'^logout/$', 'logout_view', name='logout'),
    url(r'^register/$', 'register_view', name='register'),
    url(r'^indexing.js$', 'indexing_js', name='indexing_js'),
    url(r'^bookmarklet/$', 'bookmarklet', name='bookmarklet'),
    url(r'^prefs/$', 'prefs', name='prefs'),
    url(r'^about/$', 'about', name='about'),
    url(r'^contact/$', 'contact', name='contact'),
    
    # Entries
    url(r'^entry/(?P<entry_id>[0-9]+)/$', 'entry', name='entry'),
    url(r'^entry/new', 'entry_new', name='entry_new'),
    url(r'^entry/(?P<entry_id>[0-9]+)/edit/$', 'entry_edit', 
        name='entry_edit'),
    url(r'^entry/(?P<entry_id>[0-9]+)/delete/$', 'entry_delete', 
        name='entry_delete'),
    
    # Tags (site-wide)
    url(r'^tags/$', 'tags', name='tags'),
    url(r'^tag/(?P<tag_name>[+\w:._-]+)/$', 'tag', name='tag'),
    url(r'^tag/(?P<tag_name>[+\w:._-]+)/feed/$', 'tag_feed', 
        name='tag_feed'),
    
    # Users
    url(r'^user/(?P<user_name>[a-zA-Z0-9._-]+)/$', 'user', name='user'),
    url(r'^user/(?P<user_name>[a-zA-Z0-9._-]+)/feed/$', 'user_feed', 
        name='user_feed'),
    url(r'^user/(?P<user_name>[a-zA-Z0-9._-]+)/tags/$', 'user_tags', 
        name='user_tags'),
    url(r'^user/(?P<user_name>[a-zA-Z0-9._-]+)/tag/(?P<tag_name>[+\w:._-]+)/$', 
        'user_tag', name='user_tag'),
    url(r'^user/(?P<user_name>[a-zA-Z0-9._-]+)/tag/(?P<tag_name>[+\w:._-]+)/feed/$', 
        'user_tag_feed', name='user_tag_feed'),

    # Filters
    url(r'^filter/$', 'filter_index', name='filter_index'),
    url(r'^filter/new/$', 'filter_new', name='filter_new'),

    # Legacy url pattern - redirect.  No name assigned to discourage use.
    url(r'^person/(?P<user_name>[a-zA-Z0-9._-]+)/$', 'person'),

    # Groups... 
    url(r'^group/(?P<group_name>[a-zA-Z0-9._-]+)/$', 'group', name='group'),
    url(r'^group/(?P<group_name>[a-zA-Z0-9._-]+)/feed/$', 'group_feed', 
        name='group_feed'),
    # Punt on these for now.
    #url(r'^group/(?P<group_name>[a-zA-Z0-9._]+)/tags/$', 'group_tags', 
    #    name='group_tags'),
    #url(r'^group/(?P<group_name>[a-zA-Z0-9._]+)/tag/(?P<tag_name>[a-zA-Z0-9:._-]+)/$', 
    #    'group_tag', name='group_tag'),
    #url(r'^group/(?P<group_name>[a-zA-Z0-9._]+)/tag/(?P<tag_name>[a-zA-Z0-9:._-]+)/feed/$', 
    #    'group_tag_feed', name='group_tag_feed'),

    # URLs
    url(r'^url/(?P<md5sum>[a-f0-9]{32})/$', 'url', name='url'),
    url(r'^url/(?P<md5sum>[a-f0-9]{32})/feed/$', 'url_feed', name='url_feed'),
    
    # Search
    url(r'^search/$', 'search', name='search'),
    url(r'^search/feed/$', 'search_feed', name='search_feed'),
    
    )

base/views.py
import datetime
import math
import re
import time

from django.conf import settings
from django.contrib.auth import authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login
from django.contrib import messages
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse
from django.db.models import Count
from django import forms
from django.forms.models import modelformset_factory
from django.http import Http404, HttpResponse, HttpResponseRedirect, \
    HttpResponseBadRequest
from django.http import HttpResponsePermanentRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext, loader
from django.utils import feedgenerator
from django.utils import simplejson as json
from django.views.decorators.cache import cache_control
from django.views.decorators.csrf import csrf_exempt


import feedparser
import solr

from basicauth import logged_in_or_basicauth

from base import models as m
from settings import REALM, SOLR_URL


class EntryForm (forms.Form):
    url = forms.URLField(required=True, label='URL')
    title = forms.CharField(required=True)
    tags = forms.CharField(required=False, help_text='Separate with spaces')
    is_private = forms.BooleanField(required=False)
    comment = forms.CharField(required=False, widget=forms.Textarea)
    content = forms.CharField(required=False, widget=forms.Textarea)

def apply_user_filters_to_entries (request, qs):
    # Assume the user's already been authenticated.
    for f in request.user.filters.filter(is_active=True):
        if f.attr_name == 'user':
            if f.is_exact:
                qs = qs.exclude(user__username=f.value)
            else:
                qs = qs.exclude(user__username__icontains=f.value)
        elif f.attr_name == 'tag':
            if f.is_exact:
                qs = qs.exclude(tags__tag__name=f.value)
            else:
                qs = qs.exclude(tags__tag__name__icontains=f.value)
        elif f.attr_name == 'url':
            if f.is_exact:
                qs = qs.exclude(url__value=f.value)
            else:
                qs = qs.exclude(url__value__icontains=f.value)
    return qs


def apply_user_filters_to_entry_tags (request, qs):
    # Assume the user's already been authenticated.
    # FIXME: DRY.
    for f in request.user.filters.filter(is_active=True):
        if f.attr_name == 'user':
            if f.is_exact:
                qs = qs.exclude(entry__user__username=f.value)
            else:
                qs = qs.exclude(entry__user__username__icontains=f.value)
        elif f.attr_name == 'tag':
            if f.is_exact:
                qs = qs.exclude(entry__tags__tag__name=f.value)
            else:
                qs = qs.exclude(entry__tags__tag__name__icontains=f.value)
        elif f.attr_name == 'url':
            if f.is_exact:
                qs = qs.exclude(entry__url__value=f.value)
            else:
                qs = qs.exclude(entry__url__value__icontains=f.value)
    return qs


def constrained_entries (request, requested_user=None, requested_group=None, 
    tag=None, candidate_ids=[]):
    """
    Start a base queryset of entries common to many pages.
    """
    # Never show entries from inactive user accounts.
    qs = m.Entry.objects.exclude(user__is_active=False)

    # Not sure we need this, but just in case.
    if candidate_ids:
        qs = qs.filter(id__in=candidate_ids)
        
    # Unless this gets set to false, we'll limit private users and entries.
    add_standard_restrictions = True

    # /group/ and /user/ requests are mutually exclusive.
    if requested_group:
        if requested_group.get_profile().is_private:
            # If they're a member, let them see private stuff
            if request.user in requested_group.user_set.all():
                add_standard_restrictions = False
            else:
                # Since they're not, don't let them see anything
                qs = qs.exclude(groups__name=requested_group.name)
        qs = qs.filter(groups__name=requested_group.name)
    elif requested_user:
        if requested_user == request.user:
            add_standard_restrictions = False
        qs = qs.filter(user=requested_user)

    if add_standard_restrictions:
        qs = qs.exclude(is_private=True)
        # Note:  on the following, qs.exclude...=True blows up.
        qs = qs.filter(user__userprofile__is_private=False)

    # limit to this tag
    if tag:
        qs = qs.filter(tags__tag__name=tag.name)

    # apply filters for logged-in users
    if request.user.is_authenticated():
        qs = apply_user_filters_to_entries(request, qs)

    qs = qs.order_by('-date_created')
    return qs


# Hmm, what's the best way to do this?  Punt for now and do 
# something simple.
SOLR_CONNECTION = solr.SolrConnection(settings.SOLR_URL)

def solr_connection ():
    return SOLR_CONNECTION


def get_page (request, paginator):
    try:
        page_num = int(request.GET.get('p', '1'))
        if page_num not in paginator.page_range:
            raise ValueError, 'Invalid page number'
    except ValueError:
        page_num = 1
    return paginator.page(page_num)
    

def pagify (request, qs, num_items=50):
    """
    Convenience helper to paginate out a query set.
    """
    try:
        num_items = int(num_items)
    except:
        num_items = 50
    paginator = Paginator(qs, num_items)
    page = get_page(request, paginator)
    return paginator, page


@csrf_exempt # to allow javascript bookmarklet to post
@logged_in_or_basicauth(REALM)
def entry_new (request):
    """
    Save a new URL entry. Can either come from an html form, or via some json.
    """
    request.encoding = 'utf-8'
    payload = request.META.get('CONTENT_TYPE', '')
    context = RequestContext(request)
    d = {}

    if request.method == 'POST':
        date_created = datetime.datetime.now()

        # if application/json was posted try to construct a form based on it
        if payload == 'application/json':
            # try to parse the json
            try:
                entry_json = json.loads(request.raw_post_data)
                form = EntryForm(entry_json)
                # if the json isn't right respond with an text error message
                # that explains the problem
                if not form.is_valid():
                    error_msg = ["There was a problem with your JSON:\n"]
                    for k, v in form.errors.items():
                        for e in v:
                            error_msg.append("  %s: %s" % (k, e))
                    return HttpResponseBadRequest("\n".join(error_msg),
                            mimetype="text/plain")

                # json allows you to post date_created
                if entry_json.has_key('date_created'):
                    try:
                        # parse the rfc3339 datetime
                        t = entry_json['date_created']
                        t = time.mktime(feedparser._parse_date(t))
                        date_created = datetime.datetime.fromtimestamp(t)
                    except TypeError, e:
                        return HttpResponseBadRequest("invalid date_created, should be RFC3339 compatible, e.g.  1985-04-12T23:20:50.52Z", mimetype="text/plain")
            except ValueError, e:

                return HttpResponseBadRequest("invalid json: %s" % e, 
                        mimetype="text/plain")

        # otherwise it's a standard POSTed form
        else:
            form = EntryForm(request.POST)

        if form.is_valid():
            url_str = form.cleaned_data['url']
            title = form.cleaned_data['title']
            is_private = request.user.get_profile().default_to_private_entry
            tags_orig = form.cleaned_data['tags']
            comment = form.cleaned_data['comment']
            content = form.cleaned_data['content']
            submit = request.POST.get('submit', None)
            
            # Maybe they saved this one before?  Check by url
            old_entries = m.Entry.objects.filter(user=request.user, 
                url__value=url_str)
            if old_entries:
                # If it's not 'Save anyway', they haven't confirmed yet
                if not submit == 'Save anyway':
                    return render_to_response('entry_new.html', {
                        'form': form,
                        'old_entries': old_entries,
                        }, context)
                        
            # It must be either new, or a duplicate url by choice, so go ahead
            new_entry = m.Entry(user=request.user, title=title, 
                is_private=is_private, comment=comment, content=content,
                date_created=date_created)
            
            url, was_created = m.Url.objects.get_or_create(value=url_str)
            new_entry.url = url
            
            # Save that sucker before adding many-to-manys
            new_entry.save()
            new_entry.add_tags(tags_orig)

            if payload == "application/json":
                url = reverse('entry', args=[new_entry.id])
                if was_created:
                    return HttpResponseCreated(url)
                else:
                    return HttpResponseRedirect(url)
            messages.success(request, 'Saved!')

            # If they had to confirm this, they don't need an edit screen again
            if submit == 'Save anyway':
                return HttpResponseRedirect(reverse('index'))
            # Otherwise, let them tweak it
            return HttpResponseRedirect(reverse('entry_edit', args=[new_entry.id]))
    else:
        form = EntryForm()
    return render_to_response('entry_new.html', 
        {'form': form}, context)


@logged_in_or_basicauth(REALM)
@cache_control(no_cache=True)
def entry_delete (request, entry_id):
    """
    Let a user choose to delete an entry.
    """

base/templates/about.html
{% extends "base.html" %}

{% block content %}
<h2>About</h2>

<p>
I started this project in 2003 so I could track what my friends were reading. Some other people started similar projects at the same time who were smarter or more savvy than I was.  Their friends aren't more interesting than mine, though. So here we still are.
</p>

<h2>API</h2>

<p>
If you find yourself wanting to add bookmarks programatically you can use 
the minimal API by POSTing some JSON to <em>{{ site_url }}/entry/new</em>. 
You'll need to pass along your username and password with 
<em>HTTP Basic Authentication</em>, and also
need to supply a <em>Content-type: application/json</em> request header.

Here's a minimal example with cURL:

<pre>
    curl --user user:pass \
         --header "Content-type: application/json" \
         --data '{"url": "http://example.com", "title": "Example"}' \
         {{ site_url }}/entry/new
</pre>

Here's a fuller example of the JSON that you can supply:

<pre>
    {
      "url": "http://zombo.com",
      "title": "ZOMBO",
      "comment": "found this awesome website today",
      "tags": "website awesome example",
      "content": "You can do anything at Zombo.com. The only limit is yourself.",
      "is_private": true
    }
</pre>

{% endblock %}

base/templates/bookmarklet.html
{% extends "base.html" %}

{% block content %}
<h2>Bookmarklets</h2>

<h3>For your browser</h3>

<p>
Use the bookmarklet to add links; drag it from below
into your personal toolbar.  Then, whenever you visit a page
you want to add here, click the bookmarklet.
</p>

<p>
This bookmarklet: &gt;<a id='bookmarklet' href="javascript:void(z=document.createElement('script'));void(z.language='javascript');void(z.type='text/javascript');void(z.src='{{site_url}}/indexing.js');void(document.getElementsByTagName('head')[0].appendChild(z));">unalog!</a>&lt;
will send your browser window and its page content right into unalog.
</p>


<h3>For your smartphone</h3>

<p>
Copy the text below and paste it into the URL part of a new 
bookmark in your device.  Give it the title "unalog!" or whatever
strikes your fancy.
</p>

<p style='font-size:small;border:3px #999 solid;margin-left:1em;margin-right:40%;padding:.5em;background-color:#eee'>
javascript:void(z=document.createElement('script'));
void(z.language='javascript');void(z.type='text/javascript');
void(z.src='{{site_url}}/indexing.js');
void(document.getElementsByTagName('head')[0].appendChild(z));
</p>

{% endblock %}

base/templates/contact.html
{% extends "base.html" %}

{% block content %}
<h2>Contact</h2>

<p>
Please feel free to contact me.
</p>

{% endblock %}

base/templates/delete_entry.html
{% extends "base.html" %}


{% block content %}

<h2>Delete entry {{ entry.id }}</h2>


<p>
	From {{ entry.date_created|date:"l, Y-m-d" }}:
</p>

{% include "entry.html" %}

<p>
<form action='.' method='post'>
	Are you sure you want to delete this entry?
	<input type='submit' name='submit' value='yes'>
</form>
</p>

<pre>
	{{ data }}
</pre>



{% endblock %}

base/templates/entry.html
<div class='entry xfolkentry'>

    <a class='entry-url taggedlink' href='{{ entry.url.value }}'>
    {% ifequal entry.user user %}<span class='bold'>{% endifequal %}
    {{ entry.title }}
    {% ifequal entry.user user %}</span>{% endifequal %}
    </a> <br />

    <div class='entry-metadata'>

        {% if entry.comment %}
        <div class='entry-comment description'>
            {{ entry.comment }}
        </div>
        {% endif %}

        <span class='entry-time'>{{ entry.date_created|date:"H:i" }} - </span>

        <a class='entry-user' href='{% url user entry.user.username %}'>{{ entry.user.username }}</a> 

        {% with entry.tags.count as tag_count %}
            {% ifnotequal tag_count 0 %}
                -
                {% with entry.tags.all as entry_tags %}
                    {% for entry_tag in entry_tags %}
            <a class='tag' rel='tag' href='{% url user_tag entry.user.username entry_tag.tag.name %}'>{{ entry_tag.tag.name }}</a>
                    {% endfor %}
                {% endwith %}
            {% endifnotequal %}
        {% endwith %}

        {% ifnotequal 0 entry.groups.count %}
            in group{{ entry.groups.count|pluralize }}
        {% endifnotequal %}
    
        {% for g in entry.groups.all %}
            {% if g.get_profile.is_private %}
                {% for u in g.user_set.all %}
                    {% ifequal user u %}
                <a href='{% url group g.name %}'>{{ g.name }}</a>
                    {% endifequal %}
                {% endfor %}
            {% else %}
                <a href='{% url group g.name %}'>{{ g.name }}</a>
            {% endif %}
        {% endfor %}

        {% ifnotequal entry.other_count 0 %}
            - and <a href='{% url url entry.url.md5sum %}'>{{ entry.other_count }} other{{ entry.other_count|pluralize }}</a>
        {% endifnotequal %}

        {% ifequal entry.user user %}
            <div class='entry-edit'>
                [<a href='{% url entry_edit entry.id %}'><span class='bold'>edit</span></a>]
                [<a href='{% url entry_delete entry.id %}'><span class='bold'>delete</span></a>]
            </div>
        {% endifequal %}

    </div>

</div>

base/templates/entry_new.html
{% extends "base.html" %}

{% block content %}

{% if old_entries %}
    <div id='entryset'>
        <h2>Hey!  You've saved this before.</h2>
            {% regroup old_entries by date_created.date as date_groups %}
            {% for date_group in date_groups %}
                   <h2>{{ date_group.grouper|date:"l, Y-m-d" }}</h2>
                {% for entry in date_group.list %}
                    {% include "entry.html" %}
                {% endfor %}       
            {% endfor %}
        <h2>Save it again if you like.</h2>
    </div>
{% else %}
    <h2>Add a link</h2>
{% endif %}


<p>
Don't use <acronym title='Hypertext Markup Language'>HTML</acronym>; 
tags will be turned into literal text and not rendered properly.
</p>

<p>
Private entries will only be visible to you (see "my entries")
and other members of private groups to which they are added.
</p>

<form action='{% url entry_new %}' method='POST' accept-charset='UTF-8'>
    {% csrf_token %}
    <table>
        <tbody>
            <tr>
                <th valign='top'><label for='id_url'>URL:</label></th>
                <td><input type='text' name='url' size='80' value='{{ form.data.url }}' id='id_url' /></td>
            </tr>
            <tr>
                <th valign='top'><label for='id_title'>Title:</label></th>
                <td><input type='text' name='title' size='80' value='{{ form.data.title }}' id='id_title' /></td>
            </tr>
            <tr>
                <th valign='top'><label for='id_tags'>Tags:</label></th>
                <td><input type='text' name='tags' size='80' id='id_tags' /><br />Separate with spaces</td>
            </tr>
            <tr>
                <th valign='top'><label for='id_is_private'>Is private:</label></th>
                <td><input type='checkbox' name='is_private' id='id_is_private' 
                    {% if user.get_profile.default_to_private_entry %}
                        checked='checked'
                    {% endif %}
                    /></td>
            </tr>
            <tr>
                <th valign='top'><label for='id_comment'>Comment:</label></th>
                <td><textarea id='id_comment' rows='4' cols='60' name='comment'></textarea></td>
            </tr>
            <tr>
                <th valign='top'><label for='id_content'>Content:</label></th>
                <td><textarea id='id_content' rows='10' cols='60' name='content'>{{ content }}</textarea></td>
            </tr>
            <tr>
                <td></td>
                <td><input name='submit' type='submit' value='Save anyway' /></td>
            </tr>
        </tbody>
    </table>
</form>

{% endblock %}

base/templates/footer.html
<div id='footer'>
    <p>
    brought to you by the letter DOWNTIME
    </p>
</div>

base/templates/header.html
<head>

    <title>unalog: {% block title %}{{ title }}{% endblock %}</title>
    
    <meta http-equiv="Content-Language" content="en" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <meta http-equiv="Refresh" content="3600; URL=/" />
    
    <link type="text/css" rel="stylesheet" href="/s/css/style.css" />
    <link type="text/css" rel="stylesheet" href="/s/css/style_print.css" media="print" />
    <link rel="shortcut icon" type="image/ico" href="http://unalog.com/favicon.ico" />
    
	{% if feed_url %}
    <link rel="alternate" type="application/atom+xml" title="Atom 1.0" href="{{ feed_url }}" />
    {% endif %}

</head>

base/templates/index.html
{% extends "base.html" %}

{% block content %}

{% ifnotequal title "home" %}
<h2>{{ title }}</h2>
{% endifnotequal %}

{% ifequal browse_type "user" %}
<h2><a href='{% url user browse_user_name %}'>{{ browse_user_name }}</a> 
	{% if browse_user.get_profile.url %}
	    - <a rel='me' href='{{ browse_user.get_profile.url }}'>{{ browse_user.get_profile.url }}</a> - 
	{% endif %}
	{% if tag %}
	tag "{{ tag }}"
	{% else %}
	[<a href='{% url user_tags browse_user_name %}'>tags</a>]
	{% endif %}
	</h2>
{% endifequal %}

{% ifequal browse_type "tag" %}
<h2>Tag <a href='{% url tag tag.name %}'>{{ tag.name }}</a>
	{% if browse_user %}
	for <a href='{% url user browse_user.username %}'>{{ browse_user.username }}</a>
	{% else %}
	for everyone
	{% endif %}
	</h2>
{% endifequal %}

{% ifequal browse_type "url" %}
<h2>URL <a href='{{ browse_url.value }}'>{{ browse_url.value|escape  }}</a></h2>
{% endifequal %}

{% ifequal browse_type "group" %}
<h2>Group {{ browse_group.name }}
	{% if tag %}
	tag "{{ tag }}"
	{% endif %}
	</h2>
{% endifequal %}

{% if page.object_list %}

   <div id='entryset'>

	{% regroup page.object_list|dictsortreversed:"date_created" by date_created.date as date_groups %}
	{% for date_group in date_groups %}
	    <div class='entryset-date'>
    		<h3>{{ date_group.grouper|date:"Y-m-d - l" }}</h3>
		
            {% for entry in date_group.list|dictsortreversed:"date_created.time" %}
    			{% include "entry.html" %}
            {% endfor %}       
        </div>
    {% endfor %}

   </div>

{% else %}

	<p>
		Nothing found.
	</p>

{% endif %}


	
{% if page.has_other_pages %}
	{% if query_param %}
		{% include 'query_pagination.html' %}
	{% else %}
		{% include 'pagination.html' %}
	{% endif %}
{% endif %}


{% endblock %}

base/templates/login.html
{% extends "base.html" %}


{% block content %}

<h2>Log in</h2>

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action=".">
	<table>
		<tr><td>{{ form.username.label_tag }}</td><td>{{ form.username }}</td></tr>
		<tr><td>{{ form.password.label_tag }}</td><td>{{ form.password }}</td></tr>
	</table>

	<input type="submit" value="login" />
	<input type="hidden" name="next" value="{{ next }}" />
</form>


{% endblock %}

base/templates/new_entry.html
{% extends "base.html" %}

{% block content %}

{% if old_entries %}
<h2>Hey!  You've saved this before.</h2>
	{% regroup old_entries by date_created.date as date_groups %}
	{% for date_group in date_groups %}
	   	<h2 class='timeline-daysep'>{{ date_group.grouper|date:"l, Y-m-d" }}</h2>
		{% for entry in date_group.list %}
			{% include "entry.html" %}
		{% endfor %}       
	{% endfor %}
<h2>Save it again if you like.</h2>
{% else %}
<h2>Add a link</h2>
{% endif %}


<p>
Don't use <acronym title='Hypertext Markup Language'>HTML</acronym>; 
tags will be turned into literal text and not rendered properly.
</p>

<p>
Private entries will only be visible to you (see "my entries")
and other members of private groups to which they are added.
</p>

<form action='/entry/url/new' method='POST'>
	<table>
		<tbody>
			<tr>
				<th valign='top'><label for="id_url">URL:</label></th>
				<td><input type="text" name="url" size="80" value="{{ form.data.url }}" id="id_url" /></td>
			</tr>
			<tr>
				<th valign='top'><label for="id_title">Title:</label></th>
				<td><input type="text" name="title" size="80" value="{{ form.data.title }}" id="id_title" /></td>
			</tr>
			<tr>
				<th valign='top'><label for="id_tags">Tags:</label></th>
				<td><input type="text" name="tags" size="80" id="id_tags" /><br />Separate with spaces</td>
			</tr>
			<tr>
				<th valign='top'><label for="id_is_private">Is private:</label></th>
				<td><input type="checkbox" name="is_private" id="id_is_private" /></td>
			</tr>
			<tr>
				<th valign='top'><label for="id_comment">Comment:</label></th>
				<td><textarea id="id_comment" rows="4" cols="60" name="comment"></textarea></td>
			</tr>
			<tr>
				<th valign='top'><label for="id_content">Content:</label></th>
				<td><textarea id="id_content" rows="10" cols="60" name="content">{{ content }}</textarea></td>
			</tr>
			<tr>
				<td></td>
				<td><input name='submit' type='submit' value='Save anyway' /></td>
			</tr>
		</tbody>
	</table>
</form>

{% endblock %}

base/templates/pagination.html
{% block pagination %}
<ul id='pagination'>

    {% if page.has_previous %}
    <li><a href='{{ request.path }}?p={{ page.previous_page_number }}'>Newer</a></li>
    {% endif %}

	{% if page.has_next %}
    <li><a href='{{ request.path }}?p={{ page.next_page_number }}'>Older</a></li>
	{% endif %}

</ul>
{% endblock %}

base/templates/prefs.html
{% extends "base.html" %}

{% block content %}

<h2>Update your preferences</h2>

<p>
    Add your URL if you want other users to be able to find your home page. 
    It will show up whenever someone looks at your links.
</p>
  
<p>
    "Keep account private" lets you hide all links from other users.
    They won't be able to see any of your links unless you share them through
    groups.
</p>

    {% if has_lotsa_entries %}
<p>
    <span class='bold'>Note:</span> if you change your "private" status,
    unalog will reindex your links accordingly.  This might take a while, so
    please be patient.
</p>
    {% endif %}
    
<p>
    "Links private by default" makes your new links private
    by default -- even if your account isn't private.  
</p>

<table class='gentable'>
    <thead>
    </thead>
    <tbody>
        <form method='POST' action='{% url prefs %}'>
            {% csrf_token %}
            <input id='id_user_id' name='user_id' type='hidden' value='{{ user.id }}' />
            <tr>
                <th>Your URL</th>
                <td>{{ profile_form.url }}</td>
            </tr>
            <tr>
                <th>Keep account private</th>
                <td>{{ profile_form.is_private }}</td>
            </tr>
            <tr>
                <th>Links private by default</th>
                <td>{{ profile_form.default_to_private_entry }}</td>
            </tr>
            <tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type='submit' value='update'>
                    {% if has_lotsa_entries %}
                        (will take several seconds)
                    {% endif %}
                </td>
            </tr>
        </form>
    </tbody>
</table>



{% endblock content %}